[package]
name = "bt_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
bt_manager_macro = { path = "../bt_manager_macro" }
serial_test = "3"
serde_json = "1.0"
serde = { version = "1", features = ["derive"] }
