[package]
name = "oz_bt"
version = "0.1.0"
edition = "2021"

[dependencies]
oz_bt_macro = { path = "../oz_bt_macro" }
serial_test = "4"
serde = { version = "1", features = ["derive"] }
zmq = "0.10"
bincode-next = { version = "3.1", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
heck = "0.5"
